### PR TITLE
Remove deprecation warnings. Update ember-cli-htmlbars.

### LINKED ISSUE #12: Upgrade ember-cli-htmlbars
This will get rid of these warnings in projects that depend on `ember-cli-clipboard`:

```DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
    at Function.Addon.lookup (/Users/devinus/Projects/rebelmail-dashboard/node_modules/ember-cli/lib/models/addon.js:1009:27)```

### PR DESCRIPTION
**Pull request by oscarni**
Update `ember-cli-htmlbars` to 1.0.8.

Resolves #12

### CODE REVIEW

**Comment by nikz** [comment]
:+1: from here, this works :)

**Comment by osxi** [comment]
We should remove the duplicate ember-cli-htmlbars from devDependencies. `dependencies` implies this.

**Comment by osxi** [comment]
It would also help to increment the version to something like 0.4.1 so @jkusa can just create the tag and publish the new package :)

**Comment by cibernox** [comment]
I just hit the same problem 5 minutes ago. I'm going to use your branch for now while this is not merged.

**Comment by osxi** [comment]
One last thing: ember-cli-htmlbars v1.0.10 was just released so maybe we could use `^1.0.10`?

**Comment by jkusa** [comment]
Sorry for the delay on this. I've been on holiday. 

@oscarni do you mind making the changes suggested by @osxi?

**Comment by oscarni** [comment]
Sure thing, I'm on holiday though, will probably get to a computer on Monday.

**Comment by oscarni** [comment]
@jkusa Updated to v1.0.10 :)

**Comment by jkusa** [comment]
@oscarni awesome. Thanks!

**Pull request merged**
