### PR TITLE
Prepare for FastBoot 1.0

### LINKED ISSUE #26: Fix breaking changes in FastBoot 1.0
The current `ember-cli-fastboot` releases (1.0.0-rc.1 and above) introduce breaking changes. These will most likely break your current FastBoot implementation.

See https://github.com/ember-fastboot/ember-cli-fastboot/issues/387 for more information and a guide on how to fix your addon. Also you may want to visit the `-fastboot` Slack channel to get help from other users.

*Note: this issue has been created automatically, by searching for certain patterns in your code. If you think this has been falsely created, feel free to close!*

### PR DESCRIPTION
**Pull request by kratiahuja**
Fixes #26 

PS: I haven't tested this, so please test it in an app.

cc: @jkusa

### CODE REVIEW

**Comment by jkusa** [comment]
@kratiahuja a quick test with your change, `ember-2.13.3`, and `fastboot-1.0.0-rc.5` did  not work in the dummy app. I'll see if I can dig in a little more.

**Comment by sivakumar-kailasam** [comment]
@kratiahuja @jkusa I've tried changes on an actual app and raised #28

**Comment by kratiahuja** [comment]
Curious to understand what didn't work?

**Comment by jkusa** [comment]
@kratiahuja thanks for getting the ball rolling with this PR. #28 is now merged and includes these changes along with additional logic to check for the presence of `window`.

**Pull request closed without merging**
