### PR TITLE
replace "tagName = ''" declaration with decorator

### LINKED ISSUE #356: Bug: 'cannot use elementId on a tag-less component'
```
Uncaught Error: Assertion Failed: You cannot use `elementId` on a tag-less component: <project-name@component:copy-button::ember1892>
```

**To Reproduce**

bump from `"ember-cli-clipboard": "0.13.0",` to `"ember-cli-clipboard": "0.15.0",`

**Additional context**

```
"ember-source": "~3.1.0",
```
Most likely, this is the source of this issue https://github.com/emberjs/ember.js/issues/16177

Usage of:
```
import { tagName } from '@ember-decorators/component';

@tagName('')
```
instead of:
```
tagName = '';
```
solves this issue

### PR DESCRIPTION
**Pull request by Mifrill**
closes #356

### CODE REVIEW

**Comment by Mifrill** [comment]
Hey, @jkusa can you please check this one? Not sure why tests are not running

**Comment by Mifrill** [comment]
Hey, @jkusa can you please approve workflow here for the tests run?

**Comment by Mifrill** [comment]
Hey, @jkusa They say a picture paints a thousand words, so here is a GIF which best illustrates our conversation to date....
illustrates conversation

If humour is the way to your heart, please do some updates here

**Comment by jkusa** [comment]
Haha, good one @Mifrill :) My apologies for the delay. I can't seem to find a way to approve your build. Is there something on your end you can do to re-request it? Or you could try closing then opening the PR. 

What version of ember-source are you using? `3.1.x`? This repo is passing on all LTS versions. It is kinda of bummer that we need to bring in a dependency to fix this, but let's start with getting your PR building with GH Actions.

**Comment by Mifrill** [comment]
> What version of ember-source are you using?

yeah, correct:
```
ember-source@~3.1.0:
  version "3.1.4"
```

**Comment by Mifrill** [comment]
> let's start with getting your PR building with GH Actions

Nice, sounds good for a start, I did a dedicated PR for this:
https://github.com/jkusa/ember-cli-clipboard/pull/365

**Comment by jkusa** [comment]
@Mifrill yeah it looks like the lint job ran, but not the ci. I clicked **enable** job, on my side. We shouldn't need to update the `ci.yml`. Maybe try pushing an update to the `Mifrill:bugfix/tag-name` branch to fire off the job.

**Comment by Mifrill** [comment]
It's very kind of you @jkusa! So, after the update, we have a two things here:
- shall we use ember-decorators as `devDependency` instead of dependency?
- the package.lock changes look queerly huge (`+62 −24,597`) but it's just a simple run of the `npm install`

**Comment by Mifrill** [comment]
Hey @jkusa! any updates here?

**Comment by Mifrill** [comment]
Hi, @jkusa can you please trigger CI for ember-try builds?

**Comment by jkusa** [comment]
@Mifrill the `ci` flow should be enabled now. Try pushing to the branch to trigger the job.

**Comment by Mifrill** [comment]
https://github.com/jkusa/ember-cli-clipboard/issues/356#issuecomment-934183561

**Pull request closed without merging**
