### PR TITLE
[WIP] Add code-block component

### PR DESCRIPTION
**Pull request by visualapps**
Something like first one. added a {{copy-block}} component to make block level copy. 
https://codepen.io/rake7h/full/YdZBBz

```
{{#copy-block
  clipboardText="ember install ember-cli-clipboard"
  success=(action "onSuccess")
  error=(action "onError")
  title='copy to clipboard'
  class='copy-block'
}}
<code>.......</code>
{{/copy-block}}
```

### CODE REVIEW

**Comment by jkusa** [comment]
Hi @visualapps, I am not exactly sure what you are proposing in this PR. Are you wishing to have a component that copies a block of text from a span? Are you looking for something similar to example two (Get Text From Target Element) in the demo: http://jkusa.github.io/ember-cli-clipboard/?

**Comment by visualapps** [comment]
Hi @jkusa, Yes something like example two but without a copy button. Idea is to have a block(div, code, textarea etc...)with text and onClick of block copy the text. 
example: 
https://codepen.io/rake7h/full/YdZBBz.
http://weaveworks-ui-components.s3-website-us-west-2.amazonaws.com/#/components/code

**Comment by visualapps** [comment]
Is there any way to achieve the same output with {{copy-block}}?

**Comment by jkusa** [comment]
> Is there any way to achieve the same output with {{copy-block}}?

Do you mean with `{{copy-button}}`?

If so, there is a way, albeit a bit of a work around: https://codesandbox.io/s/q76605yl4?module=%2Fapp%2Ftemplates%2Fapplication.hbs

**Comment by visualapps** [comment]
@jkusa that's awesome. thanks for the example app.

**Comment by jkusa** [comment]
@visualapps what is the status on this? Did the code example I sent meet your needs?

**Comment by visualapps** [comment]
> @visualapps what is the status on this? Did the code example I sent meet your needs?

@jkusa sorry for delay response. Yes example went as expected. Now i don't think we need to have a separate component for this, selecting target div or code with `clipboardTarget` works well with few css styling via `className`.

**Comment by jkusa** [comment]
@visualapps good to hear. Thanks!

**Pull request closed without merging**
